CC=gcc
DIR_PATH:=$(shell find . -maxdepth 1 -type d)
SRC:=$(wildcard *.c)
APP_NAME:=main
COMPILE_DATE=$(shell date  "+%Y-%m-%d %H:%M:%S %Z")
VERSION_NUM=1.0
FLAGS_RC522+=-L ./rc522/  -lrc522
FLAGS_SPI+=-L ./spi/ -lspi
FLAGS_TRANSFER+=-L ./transfer/ -ltransfer
FLAGS_RC522+=-I ./rc522 
FLAGS_SPI+=-I ./spi
FLAGS_TRANSFER+=-I ./transfer
define get_lib_name
    @echo $(notdir $(DIR_PATH))
endef
.PHONY:all
all: entry version compile
PWD = $(shell pwd)
#export LD_LIBRARY_PATH=$(PWD)/transfer/
#export LD_LIBRARY_PATH=$(PWD)/spi/
#export LD_LIBRARY_PATH=$(PWD)/rc522/
export $(PWD)
export .
entry:
	@echo '"$(CFLAGS)"'
	@echo "++++++++++++++++++++++++++++++++++++++++++++++++++++";
	@echo "                                                    ";
	@echo "      COMPILE  THE  $(APP_NAME) FOR THIS PROGRAM    ";
	@echo "                                                    ";
	@echo "++++++++++++++++++++++++++++++++++++++++++++++++++++";

version:
	@echo "-------------------------------------------------------------------" > version.h
	@echo "|         Generated by makefile, don't edit it by hand            |" >> version.h  
	@echo "-------------------------------------------------------------------" >> version.h 
	@echo "|                                                                  " >> version.h 
	@echo "|                                                                  " >> version.h 
	@echo "|                 Copyright:   (C) 2021 by yjc                     " >> version.h 
	@echo "|                 Filename:    version.h                           " >> version.h 
	@echo "|                 Description: record  the program's information   " >> version.h 
	@echo "|                 Author:      Yang Jinchai <6762641@qq.com>       " >> version.h 
	@echo "|                 version:     $(VERSION_NUM)                      " >> version.h 
	@echo "|                                                                  " >> version.h 
	@echo "|                                                                  " >> version.h 
	@echo "-------------------------------------------------------------------" >> version.h 
	@echo " " >> version.h 
	@echo 'The Makefile creation date "$(COMPILE_DATE)"' >> version.h
	@echo "The version number is $(VERSION_NUM):" >> version.h


compile: libtransfer.so librc522.so libspi.so
	$(CC) $(SRC) -o $(APP_NAME)  $(FLAGS_RC522) $(FLAGS_SPI) $(FLAGS_TRANSFER) \
		-Wl,-R $(PWD)/rc522  -Wl,-R $(PWD)/spi -Wl,-R $(PWD)/transfer

libtransfer.so: librc522.so 
	$(CC) -fPIC -shared ./transfer/transfer.c -o libtransfer.so \
		 $(FLAGS_RC522) -Wl,-R $(PWD)/rc522 
	mv libtransfer.so ./transfer
	

libspi.so:
	$(CC) -fPIC -shared ./spi/spi.c -o libspi.so \
		$(FLAGS_SPI) -Wl,-R $(PWD)/spi

	mv libspi.so ./spi

librc522.so: libspi.so
	$(CC) -fPIC -shared ./rc522/rc522.c -o librc522.so \
		$(FLAGS_SPI) -Wl,-R $(PWD)/spi
	mv librc522.so ./rc522/

.PHONY:clean
clean:
	rm -rf ./transfer/libtransfer.so 
	rm -rf ./rc522/librc522.so
	rm -rf ./spi/libspi.so
	rm -rf ./version.h
	rm -rf ./main
	rm -rf /usr/lib/libtransfer.so
	rm -rf /usr/lib/librc522.so
	rm -rf /usr/lib/libspi.sp
	rm -rf /usr/local/libspi.so
	rm -rf /usr/local/librc522.so
	rm -rf /usr/local/libtransfer.so
