-------------------------------------------------------------------
|         Generated by makefile, don't edit it by hand            |
-------------------------------------------------------------------
|                                                                  
|                                                                  
|                 Copyright:   (C) 2021 by yjc                     
|                 Filename:    version.h                           
|                 Description: record  the program's information   
|                 Author:      Yang Jinchai <6762641@qq.com>       
|                 version:     1.0                      
|                                                                  
|                                                                  
-------------------------------------------------------------------
 
The Makefile creation date "2021-04-18 11:28:13 BST"
The version number is： 1.0
